### ISSUE TITLE
(Auto) Configure

### ISSUE THREAD

**Issue by rinkevichjm** [holtrop/rscons#48]
scons has a configure facility and while rake has some, it fails completely on C++ building for example the [gem rwx](https://rubygems.org/gems/rwx/versions/0.0.1.1.dev) attempts to configure stuff with C++ and has issues with rake.

**Comment by holtrop** [comment]
Implemented a 'configure' operation (which will be automatically invoked if not previously done) in rscons 2.x branch (not yet released).

**Comment by rinkevichjm** [comment]
Nice I’ll have to try it
